apiVersion : apps/v1
kind: Deployment
metadata:
  name: book-accounting
  labels:
    app : book-accounting
spec:
  selector:
    matchLabels:
      project: book-accounting
  template:
    metadata:
      labels:
        project: book-accounting
    spec:
      containers:
        - name : book-accounting
          image: umk27/book-accounting-service:latest
          ports:
            - containerPort: 8000
      restartPolicy: Always

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: book-accounting-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: book-accounting
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: book-accounting
  labels:
    app: book-accounting
spec:
  selector:
    project: book-accounting
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8000
      targetPort: 8000
  type: LoadBalancer