apiVersion : apps/v1
kind: Deployment
metadata:
  name: book-accounting
  labels:
    app : book-accounting
spec:
  replicas: 1
  selector:
    matchLabels:
      project: book-accounting
  template:
    metadata:
      labels:
        project: book-accounting
    spec:
      containers:
        - name : book-accounting
          image: umk27/book-accounting-service:latest
          ports:
            - containerPort: 8000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: book-accounting
  labels:
    app: book-accounting
spec:
  selector:
    project: book-accounting
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8000
      targetPort: 8000
  type: LoadBalancer