apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: book-accounting
  name: book-accounting
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-accounting
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: book-accounting
    spec:
      containers:
      - image: umk27/book-accounting-service:latest
        imagePullPolicy: IfNotPresent
        name: book-accounting-service
        readinessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8000
            path: /actuator/health/liveness
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-accounting
  name: book-accounting
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: book-accounting
  sessionAffinity: None
  type: LoadBalancer